language: ruby
rvm:
  - 2.2.2
before_install: gem install bundler -v 1.10.5
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'create database json_attributes_database;' -U postgres
  - psql -U postgres -q -d json_attributes_database -f db/structure.sql
  - cp -f config/travis/database.yml config/database.yml
